wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.2
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1705910803.542858
    t:
      1:
      - 5
      - 8
      - 53
      - 55
      2:
      - 5
      - 8
      - 53
      - 55
      3:
      - 13
      - 23
      4: 3.10.13
      5: 0.16.2
      8:
      - 1
      - 5
      13: linux-x86_64
